apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80  # Port your container is listening on
  type: ClusterIP     # Internal service (use NodePort or LoadBalancer for external access)
